### ISSUE TITLE
pip install fails in clean environment

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/ga4gh-client#72]
I'm having an issue that has been addressed previously ([#774](https://github.com/ga4gh/schemas/issues/774)) in `ga4gh-schema`.

I'm trying to build a downstream app that uses ga4gh-client, but I'm having an issue with a protobuf dependency for pip install on both `ga4gh-client` and `ga4gh-schema`.

I thought it was resolved in the other issue, but it appears to still be a problem for `ga4gh-schema` installs too.

What's the recommended course of action?

```bash
(test_ga4gh)$ pip install ga4gh-client
Collecting ga4gh-client
  Using cached ga4gh_client-0.0.5.tar.gz
Collecting ga4gh_common==0.0.5 (from ga4gh-client)
Collecting ga4gh_schemas (from ga4gh-client)
  Using cached ga4gh_schemas-0.0.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/n0/dyt85yg950n9mjtl5cnkbfz00000gn/T/pip-build-p7E4qc/ga4gh-schemas/setup.py", line 37, in <module>
        process_schemas.main([PROTOCOL_VERSION, 'python'])
      File "scripts/process_schemas.py", line 222, in main
        pb.run(parsedArgs)
      File "scripts/process_schemas.py", line 207, in run
        protoc = self._getProtoc(destination_path)
      File "scripts/process_schemas.py", line 169, in _getProtoc
        protocs))
    Exception: Can't find a good protoc. Tried [u'/private/var/folders/n0/dyt85yg950n9mjtl5cnkbfz00000gn/T/pip-build-p7E4qc/ga4gh-schemas/python/protobuf/src/protoc']
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/n0/dyt85yg950n9mjtl5cnkbfz00000gn/T/pip-build-p7E4qc/ga4gh-schemas/
```

**Comment by david4096** [comment]
Thanks, this is a known issue due to the fact that the latest releases are under an alpha tag, and those releases were made without such a tag.

Try `pip install ga4gh-client --pre` and let us know! Thanks!

https://github.com/ga4gh/ga4gh-client/issues/65

**Comment by ahwagner** [comment]
awesome, that works, thanks. Maybe in the interim the install documentation should be updated to reflect this?

Either way, I appreciate the quick reply.

**Comment by david4096** [comment]
Thanks @ahwagner that's helpful feedback! The documentation on the client is very sparse. We need to provide better directions for installation and development and I've changed the issue to reflect that.
