### ISSUE TITLE
Error running against GA4GH 1000 Genomes Examples

### ISSUE THREAD

**Issue by huiaatch** [ga4gh/ga4gh-client#81]
After installing the client successfully with
pip install --pre ga4gh_client --ignore-installed --no-cache-dir

When trying to run the basic sample (https://github.com/BD2KGenomics/bioapi-examples/blob/master/python_notebooks/1kg.ipynb), I am encountering the following error:

>>> from ga4gh.client import client
>>> c = client.HttpClient("http://1kgenomes.ga4gh.org")
>>> datasets = list(c.search_datasets())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/ga4gh/client/client.py", line 89, in _run_search_request
    protocol_request, object_name, protocol_response_class)
  File "/Library/Python/2.7/site-packages/ga4gh/client/client.py", line 939, in _run_search_page_request
    response.text, protocol_response_class)
  File "/Library/Python/2.7/site-packages/ga4gh/client/client.py", line 37, in _deserialize_response
    return protocol.fromJson(json_response_string, protocol_response_class)
  File "/Library/Python/2.7/site-packages/ga4gh/schemas/protocol.py", line 154, in fromJson
    return json_format.Parse(json, protoClass())
  File "/Library/Python/2.7/site-packages/google/protobuf/json_format.py", line 369, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/Library/Python/2.7/site-packages/google/protobuf/json_format.py", line 384, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/Library/Python/2.7/site-packages/google/protobuf/json_format.py", line 415, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/Library/Python/2.7/site-packages/google/protobuf/json_format.py", line 501, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
google.protobuf.json_format.ParseError: Failed to parse datasets field: Message type "ga4gh.schemas.ga4gh.Dataset" has no field named "info".

**Comment by kozbo** [comment]
Thanks for filing this @huiaatch. This is pointing out that we haven't updated the 1kGenomes server to the latest code base. We will be doing that next week and then the notebooks will work again. Sorry for the delay.

**Comment by ahwagner** [comment]
I don't know if this has been resolved, but I'm getting a similar error:

```python
features = [feature for feature in c.search_features(feature_set_id=f_sets[0].id, reference_name="chr7", start=55249005, end=55249006)]
Traceback (most recent call last):
  File "/Users/awagner/anaconda/envs/g2p/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-19-08ca02c2bfa1>", line 1, in <module>
    features = [feature for feature in c.search_features(feature_set_id=f_sets[0].id, reference_name="chr7", start=55249005, end=55249006)]
  File "/Users/awagner/anaconda/envs/g2p/lib/python2.7/site-packages/ga4gh/client/client.py", line 58, in _run_search_request
    protocol_request, object_name, protocol_response_class)
  File "/Users/awagner/anaconda/envs/g2p/lib/python2.7/site-packages/ga4gh/client/client.py", line 822, in _run_search_page_request
    response.text, protocol_response_class)
  File "/Users/awagner/anaconda/envs/g2p/lib/python2.7/site-packages/ga4gh/client/client.py", line 37, in _deserialize_response
    return protocol.fromJson(json_response_string, protocol_response_class)
  File "/Users/awagner/anaconda/envs/g2p/lib/python2.7/site-packages/ga4gh/client/protocol.py", line 119, in fromJson
    return json_format.Parse(json, protoClass())
  File "/Users/awagner/anaconda/envs/g2p/lib/python2.7/site-packages/google/protobuf/json_format.py", line 369, in Parse
    return ParseDict(js, message, ignore_unknown_fields)
  File "/Users/awagner/anaconda/envs/g2p/lib/python2.7/site-packages/google/protobuf/json_format.py", line 384, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/Users/awagner/anaconda/envs/g2p/lib/python2.7/site-packages/google/protobuf/json_format.py", line 415, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/Users/awagner/anaconda/envs/g2p/lib/python2.7/site-packages/google/protobuf/json_format.py", line 501, in _ConvertFieldValuePair
    raise ParseError('Failed to parse {0} field: {1}'.format(name, e))
ParseError: Failed to parse features field: Failed to parse featureType field: Message type "ga4gh.schemas.ga4gh.OntologyTerm" has no field named "termId".
```

**Comment by david4096** [comment]
Hi! Sorry for the late reply! Are you still experiencing this issue? I tried it and wasn't able to replicate.

Thanks!

```
In [18]: from ga4gh.client import client

In [19]: ds = c.search_datasets().next()

In [20]: fs = c.search_feature_sets(ds.id).next()

In [21]: features = list(c.search_features(fs.id, reference_name="chr1", start=0
    ...: , end=123123))

In [22]: features[0]
Out[22]: 
id: "WyIxa2dlbm9tZXMiLCJnZW5jb2RlX3YyNGxpZnQzNyIsIjE0MDUwOTE4MzA4ODU5MiJd"
name: "exon:ENST00000456328.2:1"
gene_symbol: "DDX11L1"
[...]
```
